# Generated by Django 5.0.3 on 2024-04-09 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_timestamp', models.IntegerField(default=1712643565)),
                ('int_value', models.IntegerField(default=0)),
                ('fk_metric', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appmetrica.metric')),
            ],
        ),
        migrations.AddField(
            model_name='metric',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appmetrica.product'),
        ),
    ]
