# Generated by Django 5.0.3 on 2024-08-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmetrica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricvalue',
            name='int_timestamp',
            field=models.IntegerField(default=1724070726),
        ),
    ]
